version: "3.8"

services:
  server:
    image: v
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - 8082:8082
    command: --addr :8082
